### ISSUE TITLE
User-selectable backgrounds

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-vscode#10]
Would be nice to allow the user to select from a couple built-in stock environment maps.  PBR in particular needs a good environment to reflect on its metallic surfaces.  Ideally, the same background(s) would be available in all the rendering engines.  There would be a config setting for the preferred background.

**Comment by DormantVision** [comment]
Would also be nice to be able to rotate them.

**Comment by emackey** [comment]
Version 2.0.4 was published last night with user-configurable environment maps.

@DormantVision looks like the online viewers don't currently offer a rotation option for the environment.  We'll close this for now, but we can revisit if that becomes available.
