### ISSUE TITLE
Invite Cesium Concierge to this repo

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-vscode#106]
This repository is getting external contributions from a lot of different folks, which is amazing, thanks everyone!

Perhaps the Cesium Concierge bot could keep track of signed CLAs for us here, like it does in other AGI repos?  It's the same list of signers.

One difference is we use `CHANGELOG.md` instead of `CHANGES.md` (to conform to VSCode extension guidelines), and there's no `ThirdParty` folder.  Other than that things should be the same I think.

@ggetz could I talk you into contributing this?  😸

**Comment by pjcozzi** [comment]
@emackey great idea, just a heads up that the Cesium team is packed with several projects so I don't think @ggetz or anyone else on the team could support this right now.  Please go for it without us!

**Comment by ggetz** [comment]
@emackey I would be happy to turn on support for this repo in AWS and review/deploy changes to the concierge :+1:

**Comment by emackey** [comment]
OBE.
