### ISSUE TITLE
Babylon.js preview doesn't display model work but Cesium and Three.js do | Mac OS

### ISSUE THREAD

**Issue by kintz09** [AnalyticalGraphicsInc/gltf-vscode#116]
I just installed this extension today and while trying to test its functionality I am running into issues. We are developing an application using Babylon.js and I have a variety of gltf models that I'm trying to preview in VS Code with this extension. The models appear as expected when using the Cesium or Three.js engine, but I don't see anything when using the Babylon.js engine.

I followed the guide to debug the extension and reviewed the console for the active-frame but haven't seen any indication of the issue.

<img width="1444" alt="babylon" src="https://user-images.githubusercontent.com/10118752/42237182-f4f5f258-7eb1-11e8-957d-28377c47c6bf.png">
<img width="1443" alt="cesium" src="https://user-images.githubusercontent.com/10118752/42237188-f74c827e-7eb1-11e8-9e1a-8dea6c08151c.png">
<img width="1443" alt="three" src="https://user-images.githubusercontent.com/10118752/42237191-f91a0572-7eb1-11e8-967e-ab1b6f64dfdb.png">
<img width="798" alt="console" src="https://user-images.githubusercontent.com/10118752/42237196-fe6cbc68-7eb1-11e8-93d5-a604580411a1.png">

I'm running this on a 2016 Macbook Pro 15" with Touchbar.
macOS High Sierra version 10.13.5.
VS Code 1.24.1
glTF Tools 2.1.13

Any assistance would be appreciated! Please let me know what additional information I can supply to help debug.

**Comment by emackey** [comment]
@kintz09 Does this happen with glTF official sample models, or only your own models?

**Comment by kintz09** [comment]
@najadojo @emackey Thank you for the fast response! I hadn't stumbled across the official sample models yet. I was able to confirm that the sample models work perfectly in VS Code as well as in the babylonjs sandbox. It appears the problem is only with our models.

When testing our models in the babylonjs sandbox I received the following error:
`#/images/0: Failed to load 'layer_top_baseColor.jpg': 0`

We probably got something wrong during our export process. Thanks for the help!

**Comment by emackey** [comment]
@kintz09 No problem.  If you can't figure it out, please feel free to post a broken test model here, as a number of us have a lot of experience debugging glTF models lately.
