### ISSUE TITLE
Uncaught Error: WebGL not supported

### ISSUE THREAD

**Issue by Nelvin1475963** [AnalyticalGraphicsInc/gltf-vscode#117]

**Comment by emackey** [comment]
Hi @Nelvin1475963, try updating your video card drivers.

WebGL is needed by the preview window to show the 3D model, and it gets that from Chromium (the engine that powers Google Chrome, although in this case it's wrapped inside Electron which is what VSCode is built on).  Chromium will detect outdated video drivers, and past a certain point will disable access to WebGL.

If you have Google Chrome installed, you can visit `chrome://gpu/` to see the Chrome report on your graphics setup.
