### ISSUE TITLE
Draco compressed model fails in Three.js preview

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/gltf-vscode#118]
Hi folks

I recently started to look at draco compressed models and encountered the following issue in the preview:

![gltf_preview](https://user-images.githubusercontent.com/15689124/44297844-d8e01580-a2d8-11e8-8bff-608f7a9e57e5.png)

Babylon.js and Cesium don't seem to have problems with the model. Any ideas?
The model is the standard milk truck model, shipped by Cesium and attached here for convenience:

[DracoCompressed.zip](https://github.com/AnalyticalGraphicsInc/gltf-vscode/files/2299310/DracoCompressed.zip)

Have a nice weekend

**Comment by emackey** [comment]
I'm still seeing this error in the ThreeJS previewer.  The console says:

> on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)

/cc @najadojo Any ideas on this?

**Comment by emackey** [comment]
I believe this was fixed in version 2.2.2.

@tkazik let me know if you still see this one after upgrading to the latest version, thanks!

**Comment by tkazik** [comment]
Yes, fixed...thank you very much!
