### ISSUE TITLE
GLB to GLTF

### ISSUE THREAD

**Issue by dylangeofs** [AnalyticalGraphicsInc/gltf-vscode#130]
Is it possible to use the extension with 1.0 models?

**Comment by najadojo** [comment]
No only GLB 2.0 is supported by the extension.

**Comment by dylangeofs** [comment]
Any way to convert 1.0 GLB models to GLTF?

**Comment by najadojo** [comment]
Not with this tool chain, but if you want to take a look at the current 2.0 conversion it would probably be reasonably straight forward to add 1.0 support. [gltf-import-export](https://github.com/najadojo/gltf-import-export) is the GitHub project you'd want to fork.

**Comment by emackey** [comment]
If a command-line utility will do, I'm pretty sure [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline) can convert GLB 1.0 to glTF 2.0.
