### ISSUE TITLE
Why was the extension unpublished?

### ISSUE THREAD

**Issue by lexaknyazev** [AnalyticalGraphicsInc/gltf-vscode#131]
[Marketplace page](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode) says:
>  This extension is now unpublished from Marketplace. You can choose to uninstall it.

**Comment by xinaesthete** [comment]
I noticed that I got a message
`We gave uniunstatlled 'cesium.gltf-vscode' which was reported to be problematic`
I'm curious what issues there might have been (there's a chance I start dabbling with some multi-media-ish vscode extensions, so idly wondering what kind of general issues there might be).

**Comment by auchenberg** [comment]
See https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/132

**Comment by emackey** [comment]
Thanks @lexaknyazev.  Closing as duplicate with #132.

**Comment by emackey** [comment]
We're back on the air now.  But, users who launched VSCode today will have to manually reinstall.

![howtoinstall](https://user-images.githubusercontent.com/1235080/49128732-b035c780-f29a-11e8-961e-791420578230.png)
