### ISSUE TITLE
Your extension is affected by event stream and have been blocked

### ISSUE THREAD

**Issue by auchenberg** [AnalyticalGraphicsInc/gltf-vscode#132]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) Fix the extension, submit an update to the marketplace
2) Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

**Comment by emackey** [comment]
Hi @auchenberg, I pushed an update with the fix, and I sent email to the two addresses above.  Please unblock the extension.  Thanks!

**Comment by emackey** [comment]
Further comments in: https://github.com/Microsoft/vscode/issues/63837#issuecomment-442163996

**Comment by emackey** [comment]
The extension has been restored to the marketplace.  Users will have to manually reinstall.
