### ISSUE TITLE
Babylon previewer: Material access issue?

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/gltf-vscode#139]
Hi folks

The Babylon previewer shows the following error with a model that you will find attached further below:

![mymaterial](https://user-images.githubusercontent.com/15689124/50088917-9ede3c00-0204-11e9-8480-0c4dc6082cba.png)

The model: [F100_generic.zip](https://github.com/AnalyticalGraphicsInc/gltf-vscode/files/2686110/F100_generic.zip)

Or is this related to https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/125 and will be solved once a new version including https://github.com/AnalyticalGraphicsInc/gltf-vscode/pull/129 is published?

Thx a lot!

**Comment by bghgary** [comment]
I tried locally with the latest and it loads fine. It should work once a new version is published.

![image](https://user-images.githubusercontent.com/19158740/50132384-c270a900-023b-11e9-8039-6f6c64d7391f.png)

**Comment by emackey** [comment]
@tkazik I just published a new version, `2.2.1`.  Do you mind re-testing this?  Thanks!

**Comment by tkazik** [comment]
Solved, thanks a lot! Awesome job, guys!
