### ISSUE TITLE
copy Inspect Data treeview to clipboard

### ISSUE THREAD

**Issue by andreasplesch** [AnalyticalGraphicsInc/gltf-vscode#146]
Decoding the binary accessor data with Inspect Data is great but then one may want to use or further analyze the data. Currently, it is not possible to copy and paste from the tree view in the Inspect Data tree view. I seem to recall that in an earlier version without the sidebar it was possible copy data from the Inspect Data panel. Please do not disable selecting and copying text from the current Inspect Data view.

**Comment by bghgary** [comment]
The old view is actually still there if you Go to definition (F12 or context menu) instead of Inspect Data. I can add a context menu to copy the data in the inspect data view when I get a chance.
