### ISSUE TITLE
Scene based animations

### ISSUE THREAD

**Issue by M1ntcraft3r** [AnalyticalGraphicsInc/gltf-vscode#148]
Hi,

first of all, these glTF Tools are great, I have jsut started using it and it's a must have tool for gbl/gbTF editing, validation and creation.
I have come across a few glb files which include animations, however, these are not stored under the animations object but rather as multiple scenes.
In other words, I have a glb with 20 scenes which should be iterated (unloaded and loaded) in order to create the animation.

Inspecting the file in Code, I can clearly see all the scenes and their nodes but is there a way to animate such files using glTF Tools?
If not, it would be great to add such functionality.

Regards

Tim

**Comment by emackey** [comment]
> In other words, I have a glb with 20 scenes which should be iterated (unloaded and loaded) in order to create the animation.

Interesting.  What tools create such GLB files?  Can you share a GLB file that shows such a thing?  (GitHub allows < 10MB ZIPs to be dropped into issues).

**Comment by emackey** [comment]
Closing this until more info is known about these kind of glTFs.
