### ISSUE TITLE
Update Babylon again

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-vscode#15]
BabylonJS needs another update, to pick up BabylonJS/Babylon.js#2222.

As a result of this update, the "NormalTangentTest" model from the 2.0 sample models should have better lighting/reflections on it.

@HowardWolosky can I trouble you with this request?  Also would you like push access to this repo?

**Comment by HowardWolosky** [comment]
Sure -- I can do the update once that PR hits master.  And sure, I'll take push access as well, thanks for the offer!

**Comment by emackey** [comment]
Looks like push access was granted this morning, great!  No rush on the update here.

**Comment by emackey** [comment]
Thanks @HowardWolosky!
