### ISSUE TITLE
Babylon previewer: "script error"

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/gltf-vscode#152]
Hi folks

First of all: Congrats to your awesome work...I really appreciate it!
I recently ran into the following issue with the babylon previewer:
![vscode_gltf_tool_babylon_error](https://user-images.githubusercontent.com/15689124/52401856-05742d80-2ac3-11e9-910e-32eeb299fbcf.png)
The other two viewers display the model correctly and also babylon's online sandcastle is able to show the model, thus I think this issue might be related to this gltf-tool.

I am using the latest version (2.2.2) and the model (contains one info level issue by validator) can be found here:
[G6000_strut.zip](https://github.com/AnalyticalGraphicsInc/gltf-vscode/files/2840112/G6000_strut.zip)

Thank you for any insight!

**Comment by emackey** [comment]
@tkazik Did you just upgrade to VSCode 1.30.0 prior to this?

I just got the upgrade and I'm seeing this error now on my own models.  Looks like the BabylonJS logo is causing a CORS error.  I'll see what else I can figure out about it.

/cc @bghgary

**Comment by bghgary** [comment]
I'm investigating

**Comment by bghgary** [comment]
Looks like the new vscode broke a bunch of things. I'll see if I can fix them, but it might take some time.

**Comment by bghgary** [comment]
We might have to ask vscode folks on this. I can't explain why the svg logo and blob urls to local data are being blocked.

**Comment by bghgary** [comment]
For now, if you want this to work, please downgrade back to 1.30.

**Comment by emackey** [comment]
@bghgary Thanks for your efforts tracking this down!  I see a PR was merged into Babylon.

Random question, why is `revokeObjectURL` needed?  As a hack I tried resetting this to an empty function, and that seems to work in VSCode.  Is it still needed?  Does it free resources or memory?

**Comment by bghgary** [comment]
> Does it free resources or memory?

Yes. See https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL#Memory_management.

**Comment by emackey** [comment]
Version 2.2.3 is published!  Thanks @bghgary.
