### ISSUE TITLE
Inspecting accessor data sometimes shows incorrect values

### ISSUE THREAD

**Issue by Mknsri** [AnalyticalGraphicsInc/gltf-vscode#160]
When inspecting the accessors 5 or 7 on the attached model the inspector shows the data incorrectly or just with the wrong value.

Specifically accessor 5 repeats the same 2 matrices multiple times:
![image](https://user-images.githubusercontent.com/5314500/56852485-cf598380-6924-11e9-95b7-00e852ba788e.png)

And accessor 7 shows the first component of the vector as -0.00... when it in reality is -9.3710...
![image](https://user-images.githubusercontent.com/5314500/56852509-0334a900-6925-11e9-833a-27bf0e86a876.png)

VS Code version:
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8

Plugin version:
2.2.4

[sneik.zip](https://github.com/AnalyticalGraphicsInc/gltf-vscode/files/3124092/sneik.zip)

**Comment by bghgary** [comment]
Thanks for the report. I can confirm something is wrong. In the mean time, if you use `Go to Definition` (F12), it seems to show the correct values.

**Comment by bghgary** [comment]
I have a fix for the matrix values. I accidentally broke it in the last PR.

The accessor 7 issue is not an issue. The values are correct. The double values show as:
![image](https://user-images.githubusercontent.com/19158740/56916174-223e5280-6a6d-11e9-99f3-3c8ba27b74af.png)
But the first value is being formatted to 5 decimals places which results in `0.00000`

**Comment by emackey** [comment]
@Mknsri I'll get this fix published sometime in the next few days.

Did the accessor 7 explanation make sense to you?  The `e-9` on the end of that number makes it too small to be seen in the first five digits.  It's roughly `-0.000000009371...`

Thanks for the report!

**Comment by Mknsri** [comment]
Sure, thanks for the quick response!

**Comment by emackey** [comment]
Version 2.2.5 of gltf-vscode was just published.  Thanks for the fix @bghgary.  This version also includes an upgrade from Babylon `4.0.0-alpha.26` to `4.0.3` stable.
