### ISSUE TITLE
Is it possible to support automatic reload?

### ISSUE THREAD

**Issue by ikeough** [AnalyticalGraphicsInc/gltf-vscode#163]
This extension is fantastic, and has become an indispensable part of my glTF development kit. The one piece that I’d be interested to know whether it is possible to develop is automatic reload. When I’m viewing a glTF file, it would be ideal to have the extension’s view reload when that file changes on disk.

Apologies if this has already been suggested or already works. I’d be happy to contribute if there is a straightforward path for how to do it.

**Comment by bghgary** [comment]
It should already do this. Does it not do it for you?

**Comment by ikeough** [comment]
I had thought that this would already be enabled, but as far as I can tell, it is not. Here's the setup:

- .Net core test project containing code which uses the [gltf-CSharp-Loader](https://github.com/KhronosGroup/glTF-CSharp-Loader) to write a glTF file into the solution directory.
- VSCode with updated glTF Tools extension loaded.
- Run test. 
- Gltf file is generated.
- Hit "Preview 3D Model". Extension view opens. Looks great!
- With extension view still open, run the test again overwriting the gltf being viewed. **The view does not change.**
- Close the view and hit the "Preview 3D Model" icon again. View opens with updated glTF.

One thing to note. I am overwriting the file. I am not updating the contents of the glTF file. 

I did the same test, but after regenerating the glTF, I just clicked on one of the other engine buttons without closing and re-opening the 3D preview. In this case, when the new engine's display came up, the updated results were visible. Switching engines loads the latest. But the current engine does not update its visualization when the file is overwritten.

**Comment by bghgary** [comment]
Gotcha. I've submitted a fix.

**Comment by emackey** [comment]
Version 2.2.6 is published.

**Comment by ikeough** [comment]
One more data point here. When I first loaded the update, it didn't seem like the fix worked. Then I realized that the changes I made to the gltf were changes that would only change the `.bin`, not the `.gltf`, so reload never occurred. For those who might complain about this in the future, the solution is to make sure that you change something in the `.gltf`.

**Comment by bghgary** [comment]
Yeah, I don't think this one is easy to fix. The bin file isn't loaded by VSCode and thus it doesn't know that the file has changed.

**Comment by najadojo** [comment]
We could use [fs.watchFile](https://nodejs.org/docs/v0.4.3/api/fs.html#fs.watchFile) after collecting all the uris in the glTF.

**Comment by bghgary** [comment]
Hmm, good idea. I'll try it out in a bit.
