### ISSUE TITLE
[Feature Request] Add Filament Viewer as additional rendering engine

### ISSUE THREAD

**Issue by hybridherbst** [AnalyticalGraphicsInc/gltf-vscode#177]
https://github.com/google/filament would be a great addition to the current rendering engines as it would allow directly checking how models will look on Android SceneViewer.

**Comment by emackey** [comment]
Hey @cx20, where did you get your example code for loading a glTF into the JS version of Filament?

**Comment by emackey** [comment]
Oh maybe it was this: https://google.github.io/filament/webgl/helmet.html

**Comment by emackey** [comment]
Work in progress on a branch named `filament`.

/cc https://github.com/prideout/gltumble/issues/2
