### ISSUE TITLE
Add support for Babylon preview to load current tab content

### ISSUE THREAD

**Issue by HowardWolosky** [AnalyticalGraphicsInc/gltf-vscode#18]
I have a [PR out for Babylon.js](https://github.com/BabylonJS/Babylon.js/pull/2242) that adds support for Babylon to render glTF content that is directly loaded as opposed to through File I/O.

Once that hits Babylon.js master, we should take another drop of Babylon and update the Babylon previewer to use the tab content (`document.getElementById('gltf').textContent`) when loading instead of loading the actual file.

**Comment by emackey** [comment]
For reference, this follows some discussion started in https://github.com/AnalyticalGraphicsInc/gltf-vscode/pull/13#issuecomment-305664241

**Comment by HowardWolosky** [comment]
The PR was pulled to master.  I'm waiting for it to be "published" in a nightly so that I can just use the official [version builder](http://www.babylonjs.com/versionbuilder/) to generate the `babylon.custom.js` that we include.  The rest of the changes are already done in my [remote branch](https://github.com/HowardWolosky/gltf-vscode/commit/1ae6581b4be68de6ec90a4b766034ca2b46c3d4a).
