### ISSUE TITLE
Previewing glTF shows a blank screen

### ISSUE THREAD

**Issue by gilahd** [AnalyticalGraphicsInc/gltf-vscode#184]
When I try to preview a glTF I am seeing a blank screen (See screenshot). It used to work fine, but I think there was a recent VS Code update that might be causing the issue. Does anyone know why this would happen?
![glTF-Viewer](https://user-images.githubusercontent.com/57638790/87474145-a0463500-c5f0-11ea-8b5e-64501fa6d319.JPG)

**Comment by bghgary** [comment]
I'm guessing it's because of #183.

**Comment by Ziriax** [comment]
Facing similar problem here.

**Comment by yzthr** [comment]
Same problem. Can't preview any model.

**Comment by Ziriax** [comment]
As a temporary workaround, I'm using the user installer of VSCODE that doesn't work, and an older version of VSCODE as system installer that still works (on Windows)

**Comment by emackey** [comment]
Sorry about this, folks.  They've completely redone the way files are accessed from inside a VSCode Webview (glTF preview) window.  Given how much glTF and the various WebGL frameworks rely on relative web paths, this could be a substantial engineering change to fix it.  I'm looking into it, but there's no ETA yet.

**Comment by emackey** [comment]
Hi folks, I just published version `2.2.11`.  Restart VSCode and check the Extensions panel to see if you got the new version.  Let me know if the preview window is fixed, thanks!

**Comment by gilahd** [comment]
> 
> 
> Hi folks, I just published version `2.2.11`. Restart VSCode and check the Extensions panel to see if you got the new version. Let me know if the preview window is fixed, thanks!

It works! Thank you for the update
