### ISSUE TITLE
这个插件会导致vscode的依赖崩溃

### ISSUE THREAD

**Issue by 542154968** [AnalyticalGraphicsInc/gltf-vscode#198]
- VSCode Version:
![image](https://user-images.githubusercontent.com/25705659/97538067-c5717e80-19fa-11eb-907d-7a282b242994.png)

- OS Version:
![image](https://user-images.githubusercontent.com/25705659/97538042-bab6e980-19fa-11eb-808f-f68261f3d8b0.png)

Steps to Reproduce:

1. 在编辑js文件的时候，eslint报错会导致依赖崩溃，报错信息如下
![image](https://user-images.githubusercontent.com/25705659/97537955-90fdc280-19fa-11eb-88e9-712ab21e2682.png)

2.
![image](https://user-images.githubusercontent.com/25705659/97537972-98bd6700-19fa-11eb-8fba-3d9a5cec45b2.png)
3. 截止至发帖时，已是最新版 
![image](https://user-images.githubusercontent.com/25705659/97538033-b2f74500-19fa-11eb-8ac6-f052cfdc3239.png)
4. 关闭这个插件插件之后 不再崩溃

**Comment by HowardWolosky** [comment]
Helping out with the translation:

title: `This plug-in causes vscode dependency to crash`
4: `Don't crash again after you close this plug-in`

**Comment by emackey** [comment]
I have seen some additional crashes lately, but I don't know what changed.  I'd like to get clear steps to reproduce this in the English version, for debugging.

**Comment by 542154968** [comment]
> I have seen some additional crashes lately, but I don't know what changed. I'd like to get clear steps to reproduce this in the English version, for debugging.

1. enable glTF Tools
2. open .js File 
3. edit js file
4. boom！
![image](https://user-images.githubusercontent.com/25705659/97937388-899f3600-1db9-11eb-9102-52f438b40e0a.png)

**Comment by emackey** [comment]
Thanks!  Out of curiosity, is there a symlink (symbolic link) in the project directory?  If so, this could be the same cause as #196.

**Comment by 542154968** [comment]
> Thanks! Out of curiosity, is there a symlink (symbolic link) in the project directory? If so, this could be the same cause as #196.

This is the catalogue `/Applications/program/painite-web/src/program/door/views/index/useScroll.js`.  

Because ’-‘ caused it ？？？ emmmm

**Comment by emackey** [comment]
gltf-vscode version 2.3.2 was just published, and includes a new version of the Draco decoder that might fix this bug.  Can you re-test please?  Thanks!

**Comment by 542154968** [comment]
well done ~
