### ISSUE TITLE
Print the values in matrices in a less misleading way

### ISSUE THREAD

**Issue by Makogan** [AnalyticalGraphicsInc/gltf-vscode#199]
Currently the values in a matrix buffer are printed like this:

![image](https://user-images.githubusercontent.com/17284362/99206066-72345580-2788-11eb-8ac5-4431a0940fc8.png)

Each vector in that list is actually a column, but because they are printed horizontally the user can miss interpret them as rows. 

The vectors should be the rows of the matrix not the columns.

**Comment by emackey** [comment]
The thing you're seeing is what VSCode believes is a "tree view", so it seems there's no way to get multiple rows other than by expanding the tree:

![expanded tree screenshot](https://github.com/user-attachments/assets/e324012b-b271-47b5-b179-eedc03f18399)

But that's not really ideal.  A better option is to place the cursor at the start of the accessor in question, such as accessor 81 here:

![accessor 81 screenshot](https://github.com/user-attachments/assets/8febadba-832b-4190-a7a0-8818cdc3f13d)

And then press <kbd>ALT</kbd> + <kbd>d</kbd> for "decode'.  This opens a new text viewer with the decoded data:

![decoded screenshot](https://github.com/user-attachments/assets/078a81d6-619c-44d6-b986-9a7e33a1a5b5)

As a separate text viewer, this allows easier copying of data, etc.

**Comment by bghgary** [comment]
FWIW, there is already an option for copying the data to text via copy and paste.

![image](https://github.com/user-attachments/assets/ba1f7ac8-d2cd-4173-9d01-993632a72d78)
