### ISSUE TITLE
Can't get preview to work

### ISSUE THREAD

**Issue by smagnetize** [AnalyticalGraphicsInc/gltf-vscode#21]
I can't see how to preview a gltf file. I've tried exporting a .gltf file from Blender with default settings, then opened it in VS code, the plugin seems to be working as I get auto-completion for the JSON.

**Comment by emackey** [comment]
The default keybinding is <kbd>ALT</kbd> + <kbd>G</kbd>.

To see a list of tasks to run, press <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>P</kbd> and then type `gltf` into the task list search box.

To edit the key bindings, click File -> Preferences -> Keyboard Shortcuts, and type `gltf` into the search box for keyboard shortcuts.

I think the docs could be clarified a bit here.

**Comment by smagnetize** [comment]
Thanks!

**Comment by emackey** [comment]
The README is updated now to explain this a little better.  Thanks!
