### ISSUE TITLE
Option to disable the default hemisphere light?

### ISSUE THREAD

**Issue by echadwick-wayfair** [AnalyticalGraphicsInc/gltf-vscode#210]
A hemisphere light is added to the Babylon.js preview by default. Could an option be added to the settings for glTF-Tools to disable the addition of this light? 

Thanks!

![image](https://user-images.githubusercontent.com/40177036/105767284-df9ef800-5f28-11eb-8f97-615b69a5786e.png)

**Comment by bghgary** [comment]
Unless there is also a hemisphere light in the other viewers, I would recommend that we remove this light completely.

**Comment by emackey** [comment]
Yeah, different viewers have different lighting configurations.  I guess we should unify them to all use the same setup.  Maybe just the IBL by itself for all viewers?  But there are some effects that show better under with a high-intensity light source present.

**Comment by echadwick-wayfair** [comment]
Agree, a strong punctual is often important. I'd prefer a directional light rather than a hemisphere. The latter acts more like a flat ambient light. The IBL does a much better job of providing ambient lighting. 

It would help if the directional was optional, via Extension Settings. Perhaps also the angle and intensity could be controllable there, My default go-to angle for the key light is usually above and behind the camera's left shoulder, so we get specular/diffuse at upper left on the model, shading on the lower right.

**Comment by echadwick-wayfair** [comment]
:( This default light is quite an annoyance when editing material values, as I need to disable it each time I save the gltf, otherwise the model is blown out. It seems to overpower the sheen in Babylon.js. Can we please have a setting to disable it somehow?

![gltf-tools_default-light](https://user-images.githubusercontent.com/40177036/107098989-911e1300-67de-11eb-9fd7-0361cef9b9ef.gif)
