### ISSUE TITLE
Extension makes extension host in VScode to crash

### ISSUE THREAD

**Issue by HervePruvost** [AnalyticalGraphicsInc/gltf-vscode#213]
Hi, I am using VScode 1.52.1 ( the version delivered together with anaconda) and the gltf Tools extension make the extension host to crash. It never happens when I remove the extension. 
VScode ouputs this dialog:
"Extension host terminated unexpectedly"
Is there a fix for this problem?

![image](https://user-images.githubusercontent.com/24978853/106258655-68b27980-621e-11eb-8b57-687d392bb61e.png)

**Comment by emackey** [comment]
Hi, sorry to hear that.  What version of the extension is installed?

If you click "Open Developer Tools" (or the Help Menu -> Toggle Developer Tools) and look at the "Console" tab, are there error messages hinting at what happened?

If you could copy/paste some of those error messages here (with any personal info stripped out) that could help give some clue as to what might be triggering this.

**Comment by emackey** [comment]
Not sure if this is the same, because all internal errors lead to the same message box shown above.  But I left the extension running for a long time today (possibly with the preview window open the whole time, not sure), and got one of these.  This was in the console.  It appears to blame Draco, but I was not looking at a Draco-compressed model.

> abstractExtensionService.ts:466 Extension host terminated unexpectedly. Code:  7  Signal:  null
> _onExtensionHostCrashed @ abstractExtensionService.ts:466

> notificationsAlerts.ts:40 Extension host terminated unexpectedly.
> onDidChangeNotification @ notificationsAlerts.ts:40

> localProcessExtensionHost.ts:265 Extension Host
> localProcessExtensionHost.ts:266 

```
c:\Users\emackey\.vscode\extensions\cesium.gltf-vscode-2.3.7\node_modules\draco3dgltf\draco_decoder_gltf_nodejs.js:26
c?null:"utf8")};var ma=function(a){a=va(a,!0);a.buffer||(a=new Uint8Array(a));m(a.buffer);return a};1<process.argv.length&&(qa=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",K);a.inspect=function(){return"[Emscripten Module object]"}}else if(ab)"undefined"!=typeof read&&(va=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");
                                                                                                                                                                                                                                    ^[RuntimeError: abort(Error: read ECONNRESET). Build with -s ASSERTIONS=1 for more info.
	at process.K (c:\Users\emackey\.vscode\extensions\cesium.gltf-vscode-2.3.7\node_modules\draco3dgltf\draco_decoder_gltf_nodejs.js:15:91)
	at process.emit (events.js:327:22)	at processPromiseRejections (internal/process/promises.js:209:33)
	at processTicksAndRejections (internal/process/task_queues.js:98:32)]
```

**Comment by emackey** [comment]
I haven't seen this in a long time, and Draco has had a few updated versions land here.  Maybe this is fixed?
