### ISSUE TITLE
Babylon.js preview - meshes invisible?

### ISSUE THREAD

**Issue by echadwick-wayfair** [AnalyticalGraphicsInc/gltf-vscode#215]
Models are invisible in the preview when using Babylon.js. They are visible in the other engines (Cesium, etc.). I tried rolling back glTF Tools (currently 2.3.7) but it's also broken in 2.3.6. Maybe a problem on the Babylon side?

For example, load 2CylinderEngine.gltf from the glTF-Sample-Models repo, then alt-G to open the Preview. Only the default background color is visible. Turning on the "Show Background" doesn't work. Entering debug mode (open Inspector), I can enable the bounding boxes for meshes, but the meshes don't appear.

![image](https://user-images.githubusercontent.com/40177036/106920906-7c0b8c00-66d9-11eb-8626-a7abb08d7dfe.png)

**Comment by echadwick-wayfair** [comment]
Aha. When glTF Tools updates itself, it changes the folder name where we place custom ENV files.

It used to be:
C:\Users\echadwick\.vscode\extensions\cesium.gltf-vscode-2.3.6\environments
But now it's 
C:\Users\echadwick\.vscode\extensions\cesium.gltf-vscode-2.3.7\environments

Which means it can't find the custom env I have in the Settings, because this file has been deleted by the extension update:
![image](https://user-images.githubusercontent.com/40177036/106921414-fd631e80-66d9-11eb-93ba-daa0ae61f06b.png)

Perhaps the folder could be changed to be more persistent, not including the version number?

**Comment by emackey** [comment]
The folder name is always going to be unstable, so I don't recommend placing any custom files of your own in there.

Instead, place you custom environment somewhere else, anywhere else.  The setting here will accept an absolute path to some location of your choice.  

```
D:\Models\EnvMaps\HdriHaven\leadenhall_market_4k.hdr
```

VSCode will aggressively delete old extension versions and download new ones without warning, so it's best to keep your own files away from that folder.
