### ISSUE TITLE
Update BabylonJS again

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-vscode#22]
The Babylon engine could use another update.  They recently changed the way environments are applied to glTF models (see [f114d83](https://github.com/emackey/BabylonJS-glTFLoader/commit/f114d8345711b5a86ea2d0832181db0f8f8f2690), `index.js` new line 146 vs a function starting at old line 166).

I've started experimenting with adding environment reflections on a new branch here called `environment`, for issue #10, which I would like to get implemented before SIGGRAPH if possible.

@HowardWolosky Got any bandwidth to help out with an update?  Or if not, maybe post some instructions on the correct way to update Babylon here, thanks!

**Comment by HowardWolosky** [comment]
Instructions for how to update Babylon can be found [right in the repo](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/master/engines/Babylon/README.md).  I put in a README.md in each of the Engine folders to make it really easy for others to know how to update the engines going forward. It should be easy for _anyone_ to do a simple engine update. That being said, I'll try to get an update out shortly....
