### ISSUE TITLE
Autocompletion for extensionsUsed?

### ISSUE THREAD

**Issue by echadwick-wayfair** [AnalyticalGraphicsInc/gltf-vscode#231]
It would be helpful to add autocomplete for extensionsUsed.

Currently, autocomplete is great for adding extensions within a material. But it seems to be missing when adding extenstions to extensionsUsed. 

1. Type `"ext` and autocomplete suggests a few options
1. Click on the `extensionsUsed` suggestion
1. Within the brackets, type a quote character `"`
1. Autocomplete should suggestion the full list of KHR extensions, just as it does within a material.

![image](https://user-images.githubusercontent.com/40177036/149189087-95ac0001-4d3d-46b3-9264-c3755c70dfc6.png)

**Comment by emackey** [comment]
Hi @echadwick-wayfair, adding this autocomplete list to the `extensionsUsed` field is not easily done, for technical reasons (`extensionsUsed` is a JSON array of strings, where `extensions` is a JSON object with known properties, so the JSON schemas are quite different).

But there is a new "Quick Fix", added last November in #227, that can help you out here.  Once you've added that `KHR_materials_iridescence` to the `extensions` block, you'll see this:

![angry screenshot](https://user-images.githubusercontent.com/1235080/149547117-7c041738-d568-46b8-9540-90233da23cba.png)

The red squiggle is glTF Validator complaining I didn't mark the extension as used yet.  But notice I've put my cursor on the name of the extension, and there's a blue light-bulb in the left margin.  This is the "Quick Fix" indicator.

The same "Quick Fix" is also offered in a popup if you hover it:

![popup screenshot](https://user-images.githubusercontent.com/1235080/149548016-ddfbcbbe-7b37-4945-a346-ddd536a47ce3.png)

Clicking either of these will offer the only Quick Fix this project has to offer so far:

![quick fix screenshot](https://user-images.githubusercontent.com/1235080/149548289-63b04bd3-26f8-42a8-8041-aca97509eede.png)

Clicking that option will edit your document, possibly in a place far from your cursor, to add or update the `extensionsUsed` section.  You may not immediately see what it did, but you should immediately see the red squiggle disappear, as the glTF Validator no longer has that particular concern about your document.

![final screenshot](https://user-images.githubusercontent.com/1235080/149548908-f254be5f-1423-4ede-833d-228fcbe5fb99.png)

**Comment by echadwick-wayfair** [comment]
Oooh nice! This is great, thank you!
