### ISSUE TITLE
[cesium] gltf preview: Uncaught RuntimeError

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/gltf-vscode#247]
Type: <b>Bug</b>

The Error only occurs for the cesium engine, so it might also be a bug from cesium.
The file causing the issue:  
[test_wing.zip](https://github.com/AnalyticalGraphicsInc/gltf-vscode/files/9540119/test_wing.zip)

![image](https://user-images.githubusercontent.com/15689124/189479795-cd72ae10-ed98-4a4d-9fd6-b0932c1fd47c.png)

Extension version: 2.3.16
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|30.83GB (21.51GB free)|
|Process Argv|C:\\Users\\Mike\\Documents\\SugarSync\\10_models\\CL650\\test_wing.glb --crash-reporter-id a11f7958-da03-483e-94f9-961d2ed07a74|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by bertt** [comment]
glb has validation errors see https://github.khronos.org/glTF-Validator/
