### ISSUE TITLE
Validation error for missing bufferView in sparse accessors

### ISSUE THREAD

**Issue by elrnv** [AnalyticalGraphicsInc/gltf-vscode#249]
When validating a GLTF file with a sparse accessor that intentionally omits a bufferView, the spec permits this, however the validator complains:

<img width="666" alt="Screen Shot 2023-05-12 at 3 46 01 PM" src="https://github.com/AnalyticalGraphicsInc/gltf-vscode/assets/1807432/100ce15b-dd97-419b-8ce4-cdd787e72bed">

A sample file can be found here: https://github.com/elrnv/gltfgen/raw/master/assets/tet_and_tri_expected.glb

**Comment by bghgary** [comment]
You should probably raise this issue with the [glTF-Validator](https://github.com/KhronosGroup/glTF-Validator) and not here. @lexaknyazev

**Comment by elrnv** [comment]
@bghgary  Thank you! I raised the issue with glTF-Validator.
