### ISSUE TITLE
Unable to enable plug-ins

### ISSUE THREAD

**Issue by InamuraJIN** [AnalyticalGraphicsInc/gltf-vscode#263]
I get the message "This extension has been disabled because the current workspace is not trusted" and I cannot enable it
VS Code 1.85.1Ver

**Comment by emackey** [comment]
Sorry I don't check this repo more often.  VSCode added a workspace trust feature, and you need to trust the workspace to enable most of the extensions, including this extension.

Press <kbd>F1</kbd> and type: `Manage Workspace Trust` to find the screen where workspace trust is established.  You can trust a workspace as a one-time thing, or you can mark specific folders on your local disk as always having trusted content.

Note that if you download a malicious glTF / GLB file, one that was maliciously designed to trick this extension into executing remote code or doing something bad, trusting the workspace is a bad idea.  VSCode's posture of having workspaces untrusted-by-default is designed to protect users from this kind of thing.  But this won't happen by accident, so it's safe to trust files that you got by exporting yourself from Blender or other trusted software, or got from official collections of vetted sample models.
