### ISSUE TITLE
Buffer API changed

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-vscode#30]
Node.js documentation states that [new Buffer is deprecated](https://nodejs.org/api/buffer.html#buffer_new_buffer_array).

All instances of `new Buffer(...)` should be replaced with `Buffer.from(...)`.

**Comment by najadojo** [comment]
Started this with some other work at [treeview-update](https://github.com/najadojo/gltf-vscode/tree/treeview-update).

**Comment by emackey** [comment]
Thanks @najadojo
