### ISSUE TITLE
keyboard focus and viewer

### ISSUE THREAD

**Issue by nitrologic** [AnalyticalGraphicsInc/gltf-vscode#34]
Hi the babylon preview works well but using for example arrow keys to interact with cesium and three.js views is problematic unless the Hide UI option is selected.

**Comment by emackey** [comment]
@nitrologic Sorry I never responded to this.  The engine selection UI is part of a sandboxed webview that can't gain the input focus automatically.

Unfortunately I think the first user interaction needs to be mouse (or touch) to pass the input focus over to the webview control, no arrow keys or other keyboard input is going to make it through until that happens.
