### ISSUE TITLE
Auto-play animations in Cesium viewer

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/gltf-vscode#37]
It would be nice for the Cesium viewer to auto-play the animations like the Babylon and Three.JS viewers.

**Comment by emackey** [comment]
Actually there's animation controls in `master` now.  I haven't published yet due to an apparent bug in VSCode or its HTML viewer.  Working on making a reproduce case for that soon.

**Comment by emackey** [comment]
Reproduced in Microsoft/vscode#36155, already fixed in insiders' build.

**Comment by emackey** [comment]
Animations control panel deployed, let me know if you like it!
