### ISSUE TITLE
Add animations control panel to Babylon and Three previews

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-vscode#39]
Currently only the Cesium preview offers a control panel to turn animations on and off.

**Comment by emackey** [comment]
Would love some community contributions on this, or just some guidance on the right API calls to use on Babylon and Three.

**Comment by donmccurdy** [comment]
Related, I would suggest changing the current behavior and not playing all animations by default. Instead, only autoplay the first animation, or none at all. This change will look wrong with many of the existing sample models, but is technically correct and matches what we want to encourage authoring tools to write out.

See: https://github.com/KhronosGroup/glTF-Sample-Models/issues/108

Example workflow for correct multi-animation models: https://medium.com/@donmccurdy/creating-animated-gltf-characters-with-mixamo-and-blender-728dc120e678

**Comment by emackey** [comment]
All three preview windows have animation control panels as of version 2.1.9, published 2018-03-27.
