### ISSUE TITLE
Update project file to pull in all rendering engines as npm dependencies

### ISSUE THREAD

**Issue by HowardWolosky** [AnalyticalGraphicsInc/gltf-vscode#41]
With #35, Babylon.js is no longer statically being checked-in, and is rather being consumed as an NPM dependency.

I think it's a great idea.  It certainly simplifies the update step for that engine.  We should look at trying to do something similar for the other engines as well.

It looks like we can do it for Three:
  * [three](https://www.npmjs.com/package/three)
  * [orbit controls](https://www.npmjs.com/package/ndb-three-orbit-controls)
  * [gltf2 loader](https://www.npmjs.com/package/three-gltf2-loader)

And I guess this would work for [Cesium](https://www.npmjs.com/package/cesium) too.

This does put the onus on @emackey to be sure `npm update` is always run before doing any release, but it seems like a much easier way to maintain the project going forward.

**Comment by emackey** [comment]
I think I'm happy with the current system.  Cesium's npm package is much larger than the subset that I manually pull in here, and this feels like one of VSCode's larger extensions, so I don't think I'll migrate that to npm.
