### ISSUE TITLE
Improve ThreeJS preview window

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-vscode#47]
The embedded ThreeJS preview window here is from a simple example and doesn't have all the sophistication of @donmccurdy's excellent [viewer](https://github.com/donmccurdy/three-gltf-viewer).

Don I'm wondering if you would be willing to take a look at just the ThreeJS portion of this extension and see if there are improvements that could be made here?  The bulk of the code is in [threeView.js](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/master/pages/threeView.js), with a tiny bit of help from an HTML and a CSS file in the same folder.

To get a dev environment going, you install [VS Code](https://code.visualstudio.com/), click "Open Folder" on a clone of this repo, and hit F5 to launch the extension into the debugger.  A second copy of VSCode opens with the extension running.  You may want to edit user preferences on that copy to set your default preview engine to be ThreeJS instead of Babylon or Cesium.  Load a glTF (non-GLB) model into the editor and hit ALT-G to preview.  Not sure if that keybinding is the same on a Mac, actually I don't have a Mac here to test my extension so please report any Mac-specific bugs you find.  With the preview window open, getting to DevTools is a bit tricky, but I have [instructions here](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/e86649020070bb19b0d073a74b0d78b8c3aac6c0/src/gltfPreviewDocumentContentProvider.ts#L29-L42).  As always, code contributions require a [CLA](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/master/CONTRIBUTING.md).

Totally understand if you have no time to look at this.  Thought it wouldn't hurt at least to ask 😄

**Comment by donmccurdy** [comment]
Anything particular in mind? Animation controls per #39 would be nice I think... presumably you want to keep the available options consistent across each viewer?

**Comment by emackey** [comment]
Re-thinking this in light of recent comments on KhronosGroup/glTF#1081.  Maybe I should try to carve out the glTF previewing portion of this plugin, including the ThreeJS view, and turn them into a sub-project called `gltf-viewer-widget`.  The glTF viewer widget would include multiple engines for previewing, and could be included as the visualization for your web-based glTF viewer, included here for the VSCode preview window, and maybe elsewhere.  Could turn into a lot of work, we would need to be sure it's worth it to do this.

**Comment by emackey** [comment]
This issue is vague, but improvements are ongoing.
