### ISSUE TITLE
Add support for alternate 3D preview engines

### ISSUE THREAD

**Issue by HowardWolosky** [AnalyticalGraphicsInc/gltf-vscode#5]
I'm actually in the process of implementing this, but I'm creating this issue mostly so that you're aware that the development is going on.

I'm currently updating the 2.0 branch of this extension to allow for the preview pane to switch between Cesium, Babylon.js, Three.js and Osg.js.  It also adds a configuration option to choose what the default renderer should be, even though it also provides a menu within the preview pane itself to switch on the fly.

**Comment by emackey** [comment]
Super awesome!!  Be sure to merge in the upstream master, as it has a new feature of dataURI import/export which can be quite useful.

**Comment by emackey** [comment]
Published as version 2.0.0!
