### ISSUE TITLE
Checkerboard background on image preview

### ISSUE THREAD

**Issue by gbeatty** [AnalyticalGraphicsInc/gltf-vscode#55]
It would be nice to have a grey/white checkerboard background in the image preview window. With the current black background, images with transparent/translucent pixels can be hard to see. For example, the image below (as seen in Gimp) cannot be seen at all in the preview window.

![capture](https://user-images.githubusercontent.com/1686028/32552463-0964aef6-c462-11e7-8a2f-255494468601.PNG)

**Comment by najadojo** [comment]
I think vscode will do this directly if previewHtml is NOT used to load an image. If html is needed this is just styling the element as desired.

**Comment by najadojo** [comment]
Is resolved via [1655010](https://github.com/AnalyticalGraphicsInc/gltf-vscode/commit/16550105360a331a6b97bc2a43215b991f2cbd1a).
