### ISSUE TITLE
Preview failing for Babylon and Cesium in MacOS

### ISSUE THREAD

**Issue by donmccurdy** [AnalyticalGraphicsInc/gltf-vscode#58]
Getting errors when trying to open sample models. I tested with the WaterBottle directory and tried previewing the `.glTF` files:

<img width="1552" alt="screen shot 2017-11-11 at 3 42 24 pm" src="https://user-images.githubusercontent.com/1848368/32694528-17e1bd38-c6f7-11e7-8209-fa05f0d32f0b.png">

<img width="1552" alt="screen shot 2017-11-11 at 3 42 23 pm" src="https://user-images.githubusercontent.com/1848368/32694531-1bac685a-c6f7-11e7-800a-a2e068676f30.png">

<img width="1552" alt="screen shot 2017-11-11 at 3 43 51 pm" src="https://user-images.githubusercontent.com/1848368/32694532-22820860-c6f7-11e7-8add-ef181a9385c8.png">

**Comment by MichaelHazani** [comment]
+1. Mbp, High Sierra.

On Babylon.js preview:

`#/buffers/0: Failed to load 'scene.bin': 0 `

On Cesium:
`Cesium
Error: RuntimeError: Failed to load buffer: file://Users/mhazani/Desktop/mech_drone/scene.bin
Error
    at new t (file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:518:4127)
    at Ce.Le.t (file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:559:5999)
    at i.then (file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:516:27958)
    at file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:516:28436
    at m (file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:516:29818)
    at f (file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:516:28572)
    at n (file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:516:28096)
    at i.then (file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:516:27958)
    at file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:516:28446
    at m (file:///Users/mhazani/.vscode/extensions/cesium.gltf-vscode-2.1.0/engines/Cesium/Cesium.js:516:29818)`

On three.js there's no error, but nothing shows up. 
The model is glTF2, [a Mech drone downloaded from Sketchfab](https://sketchfab.com/models/8d06874aac5246c59edb4adbe3606e0e).

WebGL is otherwise running fine on my computer so I'm thinking this is something local.

**Comment by emackey** [comment]
Yeah there's a shortage of MacOS devices around here to test & debug.  Trying to get that problem fixed first.

**Comment by MichaelHazani** [comment]
Great to know. I’ve otherwise been loving the rest of the features and
singing this extension’s praises...

**Comment by emackey** [comment]
If you or @donmccurdy or any web developer reading this wants to take a stab before I manage to get my hands on someone else's hardware (just to borrow, of course), you can actually debug this directly from the market-installed extension, without building from source.  The instructions for [actually getting a Chrome DevTools open](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/master/CONTRIBUTING.md#debugging-the-html-preview-window-in-vscode) are sadly a bit convoluted in that they open the "wrong" DevTools before you get to the right one.  But once you get there, you can check the network tab for errors, you can break on JavaScript exceptions, all the usual stuff.  Of particular interest seems to be why the URI given for the `bin` file is not resolving.  It's an Electron environment, so local filesystem access is enabled.  What's different about the `bin` uri compared to some of the other uris that do resolve?

**Comment by MichaelHazani** [comment]
That's a good lead - I have forced PTO next week, now I know what I'll be
using it for:)

**Comment by lexaknyazev** [comment]
Same error in Ubuntu 17.10.

**Comment by lexaknyazev** [comment]
![virtualbox_ubuntu_16_11_2017_12_28_30](https://user-images.githubusercontent.com/3479527/32881195-e48850f6-cac9-11e7-855f-fd673971c796.png)

**Comment by emackey** [comment]
I have a partial fix going in branch `path-problems`.  But, this branch breaks BabylonJS previews across all platforms.  There's a bad assumption in Babylon.Tools.LoadFile that if the URL contains `file:` then it must be from dropped files, not local files with access enabled.

I'll write up a bug for them... it will be convoluted.  Also I have thoughts for a workaround here, involving either `base href` or monkey-patches on top of Babylon, neither of which are ideal...

**Comment by emackey** [comment]
Basically, on `master` now we're supplying local file URLs without the protocol.  This works fine on Windows, where the drive letter itself forms the needed clue to access a local file:

`c:/path/to/file.bin`

But on Mac and Linux systems, there's no drive letter, so, the path ends up looking like a host-relative path, not a true absolute path:

`/mnt/path/to/file.bin`

This gets interpreted with completely the wrong protocol (the custom glTF preview protocol).  The correct solution appears to be to add the intended protocol:

`file:///c:/path/to/file.bin`

`file:///mnt/path/to/file.bin`

This fixes it for Cesium and ThreeJS.  But Babylon makes a very poor assumption on [this line right here](https://github.com/BabylonJS/Babylon.js/blob/96541517193b5d7bdc19ed006ab4552e78244af5/src/Tools/babylon.tools.ts#L540), and gets confused by the presence of `file:` into not sending an XHR request for the file.  This leads to Babylon failing where the other two succeed.

**Comment by emackey** [comment]
Oh look, I was wrong.  Cesium messes up `file:` URLs too, just in a different way.  PR on the way.

**Comment by emackey** [comment]
@MichaelHazani Try out branch `path-problems-cesium-unminified`.  Does it work for you?  In particular, the sample models "NormalTangentTest" and "DamagedHelmet" both have very shiny surfaces, do they work in all three engines?

**Comment by MichaelHazani** [comment]
Checking! (Will update w/results shortly)

**Comment by MichaelHazani** [comment]
So, this *might* be user error on my side - I have zero experience developing VS Code extensions - but upon trying to load the extension folder (with the branch you specified) in VS code, I get:
![screen shot 2017-11-18 at 11 53 09](https://user-images.githubusercontent.com/10997806/32984217-320d0dc4-cc57-11e7-9e95-ca4e30dc3a9c.png)

Full error stack:
`/Applications/Visual Studio Code.app/Contents/MacOS/Electron --debugBrkPluginHost=43651 --debugId=779980fe-c93d-4076-882d-4292bb30ba3c --extensionDevelopmentPath=/Users/Michael_MBP/Desktop/gltf-vscode 
Activating extension `cesium.gltf-vscode` failed: Cannot find module '/Users/Michael_MBP/Desktop/gltf-vscode/out/src/extension'.
Activating extension `cesium.gltf-vscode` failed:  Cannot find module '/Users/Michael_MBP/Desktop/gltf-vscode/out/src/extension'
Here is the error stack:  Error: Cannot find module '/Users/Michael_MBP/Desktop/gltf-vscode/out/src/extension'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.$.J.t.getExtensionPathIndex.then.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:484450)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Function.a [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:27799)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:504789
	at t._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:504901)
	at t._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:503463)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:501641)
`

Running the latest VS Code (1.18.1). Haven't run into this issue when installing from the "store" (marketplace? Whatever MS calls their extension DB)

I'll try to troubleshoot for a while - any suggestions are welcome.

**Comment by emackey** [comment]
Try pressing Option-P (what would be CTRL-P on Windows) and typing `task watch` into the launch bar that appears.

**Comment by MichaelHazani** [comment]
(Sorry for deleting the previous comment; I thought it was related to forgetting to yarn beforehand, but it persists and is probably unrelated)
Getting a `The terminal process terminated with exit code: 254` even on `task watch`...

**Comment by emackey** [comment]
What version of node is installed?  I'm using 8.9.0, and older versions may not work.  Are you opening the root folder of gltf-vscode in VSCode for this?  (Meaning, you're not trying to "install" the extension from the source tree itself, right?)

**Comment by MichaelHazani** [comment]
Hmm. Upgrading 8.7 to 9.2 didn't solve the issue - same errors. 
And yes, exactly, I'm opening the gltf-vscode folder and hitting F5.

btw - @donmccurdy, have you had any luck loading and running the extension locally (on either branch)?

**Comment by MichaelHazani** [comment]
Also, this could still be a path error. 
`Activating extension `cesium.gltf-vscode` failed: Cannot find module '/Users/Michael_MBP/Desktop/gltf-vscode/out/src/extension'.
extensionHostProcess.js:4`

Clearly, "out" doesn't belong there - the path should be "gltf-vscode/src/extension". But it's nontrivial to debug - I'm not sure where the config for that path is set...

**Comment by emackey** [comment]
"out/src" is where the compiled files go.  There's no `extension` subfolder under that.  You should see some `.js` and some `.js.map` files in `out/src` after you compile it.

**Comment by MichaelHazani** [comment]
Didn't realize I had to compile first! The local dev instructions in the VS Code docs could be clearer...

working on Babylon. Cesium is throwing an error because apparently the model uses a KHR extension (understandable), and still nothing on threejs - gonna try on a simpler model.

![screen shot 2017-11-18 at 14 23 43](https://user-images.githubusercontent.com/10997806/32985281-2dc78ebe-cc6c-11e7-8c22-1bd76c00ee96.png)

**Comment by emackey** [comment]
The `task watch` thing is the compile step.  There should be a status bar at the bottom with a number `2` next to a wrench+screwdriver icon, showing two watchers running.

Glad you got it working!  And yes we expect the KHR extension message, we're going to add support for that to Cesium at some point.  I think there's still some lingering initial scale/position problems in both the Cesium and ThreeJS viewers, I need to look into that too.

**Comment by MichaelHazani** [comment]
Okay, got the simple red box from the sample models working on all three engines. Beautiful!

**Comment by emackey** [comment]
Will do.  I think this branch is basically ready to go, except that it's using a not-yet-official branch of Cesium.  Once AnalyticalGraphicsInc/cesium#5989 gets reviewed & merged, this will be ready.

**Comment by emackey** [comment]
Published as `2.1.2`
