### ISSUE TITLE
Commands aren't found in the 2.1.0 update.

### ISSUE THREAD

**Issue by najadojo** [AnalyticalGraphicsInc/gltf-vscode#62]
Just updated and on a clean machine and the commands aren't present.  Basically nothing in the extension works.

**Comment by najadojo** [comment]
Repro steps: 
close all editor buffers
restart vscode
attempt to execute GLB import

expected: glb import opens file open dialog
actual: nothing (or error if in debugging)

**Comment by emackey** [comment]
Version 2.1.1 is now published.  Thanks again!
