### ISSUE TITLE
Validator errors don't go away after closing file

### ISSUE THREAD

**Issue by bghgary** [AnalyticalGraphicsInc/gltf-vscode#72]
Repro:
1. Open a glTF file that has validation errors.
2. Close the file.

Validation errors remain in the Problems pane.

**Comment by emackey** [comment]
I've seen that happen sometimes.  There's code that's supposed to [make that not happen](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/e8580e49f909ef0f0ab95fd2c7cb9c472d9b9726/server/src/server.ts#L127-L128), but apparently it doesn't always work.

**Comment by najadojo** [comment]
This is because of vscode optimizations, see [#13363](https://github.com/Microsoft/vscode/issues/13363#issuecomment-252406364)

**Comment by emackey** [comment]
Thanks @najadojo.  That issue looks like it was resolved in October last year though, into v1.7.0.  Could it have been reintroduced somehow?  Or are we seeing something new?

**Comment by emackey** [comment]
Oh hey.  The source I quoted above isn't published yet, and the source for what's published now is quite different.  This may be a bug that @najadojo already fixed for us.

There's a December release of Cesium happening tomorrow, and I plan to bring that into the branch that fixes the Mac path problems, and then merge & publish.

**Comment by najadojo** [comment]
Its possible I made it better as I'm not seeing the problem when using the extension with my changes now. But I've also seen the behavior described above while doing development recently.

**Comment by emackey** [comment]
@bghgary Can you update to `2.1.2` and retest?  Thanks!

**Comment by bghgary** [comment]
Seems better now. 👍
