### ISSUE TITLE
Starting Project Polly animation in the Cesium viewer causes error

### ISSUE THREAD

**Issue by najadojo** [AnalyticalGraphicsInc/gltf-vscode#75]
Repro Steps:

1. Load [project_polly.gltf](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/polly/project_polly.gltf)
2. Alt-G to preview model
3. Select Cesium and wait for model to load again
4. Select aniamtions: 0

Expected:
Animation plays

Actual:
Error shown:
Uncaught TypeError: Cannot read property 'name' of undefined

Of note this file loaded correctly in the previous version of Cesium.

**Comment by emackey** [comment]
Looks like ThreeJS is broken too.

**Comment by emackey** [comment]
Ahh look at that, the Cesium one is my fault.  The API changed and I forgot to update it here.  Fix soon.

**Comment by emackey** [comment]
This is published now in `2.1.3`
