### ISSUE TITLE
Misleading navigation for KHR_draco_mesh_compression

### ISSUE THREAD

**Issue by lexaknyazev** [AnalyticalGraphicsInc/gltf-vscode#89]
This check
https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/e5ce897cff6d77c069e3202248a1fbffe2b4f334/server/src/server.ts#L432-L434
isn't precise enough so it leads to
![image](https://user-images.githubusercontent.com/3479527/37567843-2e1b2604-2ae6-11e8-922d-d3b44052f854.png)

These indices are Draco's internal pointers.

**Comment by emackey** [comment]
Thanks @lexaknyazev.

@najadojo When time permits can you take a look?

**Comment by najadojo** [comment]
I haven't spent much time looking at the Draco extension yet but I assume I could create the same data view that I can with the core vertex buffers. I'll look into making such a modification.

**Comment by emackey** [comment]
So @lexaknyazev... Now that this fix is in master (not published yet)... When do we get Draco support in the validator?  😁 

![nodracovalidation](https://user-images.githubusercontent.com/1235080/37684202-a9ed3d64-2c65-11e8-9b18-c71b061d4749.png)

**Comment by emackey** [comment]
Version 2.1.7 is now published.

**Comment by lexaknyazev** [comment]
**Go to Definition** on `indices` or attributes within `KHR_draco_mesh_compression` yields
> ERROR: Can no longer find document in editor: `path`

**Comment by najadojo** [comment]
This is working for me after updating to the released build... can you provide more explicit repro steps? I've found that VSCode sometimes closes the original document (when it shows the name in italics) and this messes up the processing we do to do the navigation.

**Comment by lexaknyazev** [comment]
1. VSCode `1.21.1`, plugin `2.1.7`.
2. Open folder (e.g. `glTF-Sample-Models\2.0\`).
3. Click on a glTF file **once** (e.g. `Avocado\glTF-Draco\Avocado.gltf`).
4. File opens in a new tab with the name in _italics_.
5. JSON navigation works as expected.
6. Ctrl-hover on `indices` or any attribute. Tool-tip shows some numbers.
7. Ctrl-click on `indices` or any attribute. A new tab with error replaces the tab with the asset.

**Comment by lexaknyazev** [comment]
Could external navigation event switch opened file from preview mode to regular?

**Comment by emackey** [comment]
As far as I know, the closing behavior is out of our control, and is intentional (for example when you use "Go to definition" multiple times in a row to jump from one file to the next, none of the intermediate files remain open).  I'm curious if @najadojo knows more or has contacts that we should reach out to on this.  But my thinking is we're kind of stuck with it.

The good news is, if a user makes any modifications to one of these name-in-italics documents, it immediately becomes a normal permanent document, so is not subject to auto-closing like this.

**Comment by najadojo** [comment]
I have a fix for this issue; if the document isn't an open editor then read in the file directly.

**Comment by emackey** [comment]
Version 2.1.8 is published.
