### ISSUE TITLE
Outline shows negative size on compressed models

### ISSUE THREAD

**Issue by lexaknyazev** [AnalyticalGraphicsInc/gltf-vscode#91]
**glTF-Sample-Models/2.0/Avocado/glTF-Draco/Avocado.gltf**

![image](https://user-images.githubusercontent.com/3479527/37702669-b97a5a9e-2d0c-11e8-876b-efd3b17cc9f9.png)

Also, selecting `Other` selects the whole JSON.

**Comment by najadojo** [comment]
That compression really works!

The selection is expected; do you have an alternate behavior suggestion?

**Comment by lexaknyazev** [comment]
> do you have an alternate behavior suggestion?

Just don't change existing selection and cursor position. Currently, it selects everything and centers vertical scrollbar.

**Comment by emackey** [comment]
Version 2.1.8 is published.
